import * as Emotive from 'emotive';
import React from 'react';

export declare const Css: typeof Emotive.Css;
export declare const Method: typeof Emotive.Method;
export declare const Length: typeof Emotive.Length;
export declare const Angle: typeof Emotive.Angle;
export declare const Time: typeof Emotive.Time;
export declare const Frequency: typeof Emotive.Frequency;
export declare const Resolution: typeof Emotive.Resolution;
export declare const Keyword: typeof Emotive.Keyword;
export declare const Color: typeof Emotive.Color;
export declare const Unit: typeof Emotive.Unit;
export declare const Property: typeof Emotive.Property;
export declare const Query: typeof Emotive.Query;
export declare const Pseudo: typeof Emotive.Pseudo;
export declare const Element: typeof Emotive.Element;

export declare class Condition {
    condition: string;
    styles: Emotive.Sheet[];
}

export declare function Selector(selector: string): (...styles: Emotive.Sheet[]) => Condition;

export declare function Media(query: string): (...styles: Emotive.Sheet[]) => Condition;

export declare const Styled: {
    component: (base: any) => (...properties: Emotive.Sheet[]) => React.Component,
    // HTML
    a: (...properties) => React.Component,
    abbr: (...properties) => React.Component,
    address: (...properties) => React.Component,
    area: (...properties) => React.Component,
    article: (...properties) => React.Component,
    aside: (...properties) => React.Component,
    audio: (...properties) => React.Component,
    b: (...properties) => React.Component,
    base: (...properties) => React.Component,
    bdi: (...properties) => React.Component,
    bdo: (...properties) => React.Component,
    big: (...properties) => React.Component,
    blockquote: (...properties) => React.Component,
    body: (...properties) => React.Component,
    br: (...properties) => React.Component,
    button: (...properties) => React.Component,
    canvas: (...properties) => React.Component,
    caption: (...properties) => React.Component,
    cite: (...properties) => React.Component,
    code: (...properties) => React.Component,
    col: (...properties) => React.Component,
    colgroup: (...properties) => React.Component,
    data: (...properties) => React.Component,
    datalist: (...properties) => React.Component,
    dd: (...properties) => React.Component,
    del: (...properties) => React.Component,
    details: (...properties) => React.Component,
    dfn: (...properties) => React.Component,
    dialog: (...properties) => React.Component,
    div: (...properties) => React.Component,
    dl: (...properties) => React.Component,
    dt: (...properties) => React.Component,
    em: (...properties) => React.Component,
    embed: (...properties) => React.Component,
    fieldset: (...properties) => React.Component,
    figcaption: (...properties) => React.Component,
    figure: (...properties) => React.Component,
    footer: (...properties) => React.Component,
    form: (...properties) => React.Component,
    h1: (...properties) => React.Component,
    h2: (...properties) => React.Component,
    h3: (...properties) => React.Component,
    h4: (...properties) => React.Component,
    h5: (...properties) => React.Component,
    h6: (...properties) => React.Component,
    head: (...properties) => React.Component,
    header: (...properties) => React.Component,
    hgroup: (...properties) => React.Component,
    hr: (...properties) => React.Component,
    html: (...properties) => React.Component,
    i: (...properties) => React.Component,
    iframe: (...properties) => React.Component,
    img: (...properties) => React.Component,
    input: (...properties) => React.Component,
    ins: (...properties) => React.Component,
    kbd: (...properties) => React.Component,
    keygen: (...properties) => React.Component,
    label: (...properties) => React.Component,
    legend: (...properties) => React.Component,
    li: (...properties) => React.Component,
    link: (...properties) => React.Component,
    main: (...properties) => React.Component,
    map: (...properties) => React.Component,
    mark: (...properties) => React.Component,
    menu: (...properties) => React.Component,
    menuitem: (...properties) => React.Component,
    meta: (...properties) => React.Component,
    meter: (...properties) => React.Component,
    nav: (...properties) => React.Component,
    noindex: (...properties) => React.Component,
    noscript: (...properties) => React.Component,
    object: (...properties) => React.Component,
    ol: (...properties) => React.Component,
    optgroup: (...properties) => React.Component,
    option: (...properties) => React.Component,
    output: (...properties) => React.Component,
    p: (...properties) => React.Component,
    param: (...properties) => React.Component,
    picture: (...properties) => React.Component,
    pre: (...properties) => React.Component,
    progress: (...properties) => React.Component,
    q: (...properties) => React.Component,
    rp: (...properties) => React.Component,
    rt: (...properties) => React.Component,
    ruby: (...properties) => React.Component,
    s: (...properties) => React.Component,
    samp: (...properties) => React.Component,
    script: (...properties) => React.Component,
    section: (...properties) => React.Component,
    select: (...properties) => React.Component,
    small: (...properties) => React.Component,
    source: (...properties) => React.Component,
    span: (...properties) => React.Component,
    strong: (...properties) => React.Component,
    style: (...properties) => React.Component,
    sub: (...properties) => React.Component,
    summary: (...properties) => React.Component,
    sup: (...properties) => React.Component,
    table: (...properties) => React.Component,
    tbody: (...properties) => React.Component,
    td: (...properties) => React.Component,
    textarea: (...properties) => React.Component,
    tfoot: (...properties) => React.Component,
    th: (...properties) => React.Component,
    thead: (...properties) => React.Component,
    time: (...properties) => React.Component,
    title: (...properties) => React.Component,
    tr: (...properties) => React.Component,
    track: (...properties) => React.Component,
    u: (...properties) => React.Component,
    ul: (...properties) => React.Component,
    var: (...properties) => React.Component,
    video: (...properties) => React.Component,
    wbr: (...properties) => React.Component,
    webview: (...properties) => React.Component,

    //SVG
    svg: (...properties) => React.Component,
    animate: (...properties) => React.Component,
    animateTransform: (...properties) => React.Component,
    circle: (...properties) => React.Component,
    clipPath: (...properties) => React.Component,
    defs: (...properties) => React.Component,
    desc: (...properties) => React.Component,
    ellipse: (...properties) => React.Component,
    feBlend: (...properties) => React.Component,
    feColorMatrix: (...properties) => React.Component,
    feComponentTransfer: (...properties) => React.Component,
    feComposite: (...properties) => React.Component,
    feConvolveMatrix: (...properties) => React.Component,
    feDiffuseLighting: (...properties) => React.Component,
    feDisplacementMap: (...properties) => React.Component,
    feDistantLight: (...properties) => React.Component,
    feFlood: (...properties) => React.Component,
    feFuncA: (...properties) => React.Component,
    feFuncB: (...properties) => React.Component,
    feFuncG: (...properties) => React.Component,
    feFuncR: (...properties) => React.Component,
    feGaussianBlur: (...properties) => React.Component,
    feImage: (...properties) => React.Component,
    feMerge: (...properties) => React.Component,
    feMergeNode: (...properties) => React.Component,
    feMorphology: (...properties) => React.Component,
    feOffset: (...properties) => React.Component,
    fePointLight: (...properties) => React.Component,
    feSpecularLighting: (...properties) => React.Component,
    feSpotLight: (...properties) => React.Component,
    feTile: (...properties) => React.Component,
    feTurbulence: (...properties) => React.Component,
    filter: (...properties) => React.Component,
    foreignObject: (...properties) => React.Component,
    g: (...properties) => React.Component,
    image: (...properties) => React.Component,
    line: (...properties) => React.Component,
    linearGradient: (...properties) => React.Component,
    marker: (...properties) => React.Component,
    mask: (...properties) => React.Component,
    metadata: (...properties) => React.Component,
    path: (...properties) => React.Component,
    pattern: (...properties) => React.Component,
    polygon: (...properties) => React.Component,
    polyline: (...properties) => React.Component,
    radialGradient: (...properties) => React.Component,
    rect: (...properties) => React.Component,
    stop: (...properties) => React.Component,
    switch: (...properties) => React.Component,
    symbol: (...properties) => React.Component,
    text: (...properties) => React.Component,
    textPath: (...properties) => React.Component,
    tspan: (...properties) => React.Component,
    use: (...properties) => React.Component,
    view: (...properties) => React.Component
};
